"""
Comprehensive Israel localities database - cities, towns, villages, settlements
with Hebrew names and GPS coordinates
"""

ISRAEL_LOCALITIES = [
    # Major Cities
    {"name": "ירושלים", "name_en": "Jerusalem", "lat": 31.7683, "lng": 35.2137, "region": "ירושלים"},
    {"name": "תל אביב-יפו", "name_en": "Tel Aviv-Yafo", "lat": 32.0853, "lng": 34.7818, "region": "תל אביב"},
    {"name": "חיפה", "name_en": "Haifa", "lat": 32.7940, "lng": 34.9896, "region": "חיפה"},
    {"name": "ראשון לציון", "name_en": "Rishon LeZion", "lat": 31.9730, "lng": 34.7925, "region": "מרכז"},
    {"name": "פתח תקווה", "name_en": "Petah Tikva", "lat": 32.0841, "lng": 34.8878, "region": "מרכז"},
    {"name": "אשדוד", "name_en": "Ashdod", "lat": 31.8044, "lng": 34.6553, "region": "דרום"},
    {"name": "נתניה", "name_en": "Netanya", "lat": 32.3215, "lng": 34.8532, "region": "השרון"},
    {"name": "באר שבע", "name_en": "Beer Sheva", "lat": 31.2520, "lng": 34.7915, "region": "דרום"},
    {"name": "חולון", "name_en": "Holon", "lat": 32.0158, "lng": 34.7875, "region": "תל אביב"},
    {"name": "בני ברק", "name_en": "Bnei Brak", "lat": 32.0834, "lng": 34.8331, "region": "תל אביב"},
    {"name": "רמת גן", "name_en": "Ramat Gan", "lat": 32.0682, "lng": 34.8249, "region": "תל אביב"},
    {"name": "אשקלון", "name_en": "Ashkelon", "lat": 31.6688, "lng": 34.5743, "region": "דרום"},
    {"name": "רחובות", "name_en": "Rehovot", "lat": 31.8928, "lng": 34.8113, "region": "מרכז"},
    {"name": "בת ים", "name_en": "Bat Yam", "lat": 32.0171, "lng": 34.7510, "region": "תל אביב"},
    {"name": "הרצליה", "name_en": "Herzliya", "lat": 32.1629, "lng": 34.7916, "region": "השרון"},
    {"name": "כפר סבא", "name_en": "Kfar Saba", "lat": 32.1780, "lng": 34.9068, "region": "השרון"},
    {"name": "חדרה", "name_en": "Hadera", "lat": 32.4340, "lng": 34.9196, "region": "חיפה"},
    {"name": "מודיעין-מכבים-רעות", "name_en": "Modiin", "lat": 31.8969, "lng": 35.0104, "region": "מרכז"},
    {"name": "נצרת", "name_en": "Nazareth", "lat": 32.6996, "lng": 35.3035, "region": "צפון"},
    {"name": "לוד", "name_en": "Lod", "lat": 31.9520, "lng": 34.8952, "region": "מרכז"},
    {"name": "רמלה", "name_en": "Ramla", "lat": 31.9275, "lng": 34.8697, "region": "מרכז"},
    {"name": "רעננה", "name_en": "Ra'anana", "lat": 32.1845, "lng": 34.8697, "region": "השרון"},
    {"name": "נהריה", "name_en": "Nahariya", "lat": 33.0060, "lng": 35.0980, "region": "צפון"},
    {"name": "גבעתיים", "name_en": "Givatayim", "lat": 32.0714, "lng": 34.8122, "region": "תל אביב"},
    {"name": "הוד השרון", "name_en": "Hod HaSharon", "lat": 32.1533, "lng": 34.8882, "region": "השרון"},
    {"name": "עכו", "name_en": "Acre", "lat": 32.9272, "lng": 35.0764, "region": "צפון"},
    {"name": "כרמיאל", "name_en": "Karmiel", "lat": 32.9190, "lng": 35.2963, "region": "צפון"},
    {"name": "אילת", "name_en": "Eilat", "lat": 29.5581, "lng": 34.9482, "region": "דרום"},
    {"name": "טבריה", "name_en": "Tiberias", "lat": 32.7960, "lng": 35.5300, "region": "צפון"},
    {"name": "עפולה", "name_en": "Afula", "lat": 32.6080, "lng": 35.2880, "region": "צפון"},
    {"name": "קריית שמונה", "name_en": "Kiryat Shmona", "lat": 33.2072, "lng": 35.5712, "region": "צפון"},
    {"name": "קריית גת", "name_en": "Kiryat Gat", "lat": 31.6100, "lng": 34.7642, "region": "דרום"},
    {"name": "קריית ביאליק", "name_en": "Kiryat Bialik", "lat": 32.8292, "lng": 35.0830, "region": "חיפה"},
    {"name": "קריית מוצקין", "name_en": "Kiryat Motzkin", "lat": 32.8375, "lng": 35.0770, "region": "חיפה"},
    {"name": "קריית אתא", "name_en": "Kiryat Ata", "lat": 32.8100, "lng": 35.1100, "region": "חיפה"},
    {"name": "קריית ים", "name_en": "Kiryat Yam", "lat": 32.8540, "lng": 35.0694, "region": "חיפה"},
    {"name": "אור יהודה", "name_en": "Or Yehuda", "lat": 32.0308, "lng": 34.8553, "region": "תל אביב"},
    {"name": "צפת", "name_en": "Safed", "lat": 32.9649, "lng": 35.4963, "region": "צפון"},
    {"name": "דימונה", "name_en": "Dimona", "lat": 31.0680, "lng": 35.0330, "region": "דרום"},
    {"name": "נס ציונה", "name_en": "Ness Ziona", "lat": 31.9330, "lng": 34.7985, "region": "מרכז"},
    {"name": "יבנה", "name_en": "Yavne", "lat": 31.8785, "lng": 34.7394, "region": "מרכז"},
    {"name": "אור עקיבא", "name_en": "Or Akiva", "lat": 32.5060, "lng": 34.9200, "region": "חיפה"},
    {"name": "טירת כרמל", "name_en": "Tirat Carmel", "lat": 32.7590, "lng": 34.9710, "region": "חיפה"},
    {"name": "עראבה", "name_en": "Arraba", "lat": 32.8520, "lng": 35.3390, "region": "צפון"},
    {"name": "סכנין", "name_en": "Sakhnin", "lat": 32.8640, "lng": 35.3000, "region": "צפון"},
    {"name": "טמרה", "name_en": "Tamra", "lat": 32.8560, "lng": 35.1980, "region": "צפון"},
    {"name": "שפרעם", "name_en": "Shefaram", "lat": 32.8060, "lng": 35.1710, "region": "צפון"},
    {"name": "אום אל-פחם", "name_en": "Umm al-Fahm", "lat": 32.5170, "lng": 35.1530, "region": "חיפה"},
    {"name": "טייבה", "name_en": "Tayibe", "lat": 32.2660, "lng": 35.0080, "region": "מרכז"},
    {"name": "קלנסואה", "name_en": "Qalansawe", "lat": 32.2830, "lng": 34.9830, "region": "מרכז"},
    {"name": "באקה אל-גרבייה", "name_en": "Baqa al-Gharbiyye", "lat": 32.4180, "lng": 35.0400, "region": "חיפה"},
    {"name": "נוף הגליל", "name_en": "Nof HaGalil", "lat": 32.7199, "lng": 35.3223, "region": "צפון"},
    {"name": "מגדל העמק", "name_en": "Migdal HaEmek", "lat": 32.6712, "lng": 35.2418, "region": "צפון"},
    {"name": "יקנעם עילית", "name_en": "Yokneam Illit", "lat": 32.6592, "lng": 35.1089, "region": "צפון"},
    {"name": "זכרון יעקב", "name_en": "Zikhron Yaakov", "lat": 32.5716, "lng": 34.9530, "region": "חיפה"},
    {"name": "פרדס חנה-כרכור", "name_en": "Pardes Hanna-Karkur", "lat": 32.4723, "lng": 34.9683, "region": "חיפה"},
    {"name": "בנימינה-גבעת עדה", "name_en": "Binyamina-Givat Ada", "lat": 32.5170, "lng": 34.9460, "region": "חיפה"},
    {"name": "קיסריה", "name_en": "Caesarea", "lat": 32.5000, "lng": 34.8900, "region": "חיפה"},
    {"name": "עתלית", "name_en": "Atlit", "lat": 32.6880, "lng": 34.9400, "region": "חיפה"},
    {"name": "נשר", "name_en": "Nesher", "lat": 32.7710, "lng": 35.0400, "region": "חיפה"},
    {"name": "יהוד-מונוסון", "name_en": "Yehud-Monosson", "lat": 32.0330, "lng": 34.8830, "region": "מרכז"},
    {"name": "גני תקווה", "name_en": "Ganei Tikva", "lat": 32.0605, "lng": 34.8770, "region": "מרכז"},
    {"name": "קריית אונו", "name_en": "Kiryat Ono", "lat": 32.0580, "lng": 34.8556, "region": "תל אביב"},
    {"name": "גבעת שמואל", "name_en": "Givat Shmuel", "lat": 32.0761, "lng": 34.8472, "region": "מרכז"},
    {"name": "אלעד", "name_en": "Elad", "lat": 32.0520, "lng": 34.9510, "region": "מרכז"},
    {"name": "ראש העין", "name_en": "Rosh HaAyin", "lat": 32.0953, "lng": 34.9563, "region": "מרכז"},
    {"name": "שוהם", "name_en": "Shoham", "lat": 31.9961, "lng": 34.9471, "region": "מרכז"},
    {"name": "גדרה", "name_en": "Gedera", "lat": 31.8140, "lng": 34.7790, "region": "מרכז"},
    {"name": "מזכרת בתיה", "name_en": "Mazkeret Batya", "lat": 31.8510, "lng": 34.7880, "region": "מרכז"},
    {"name": "קדימה-צורן", "name_en": "Kadima-Zoran", "lat": 32.2770, "lng": 34.9170, "region": "השרון"},
    {"name": "כפר יונה", "name_en": "Kfar Yona", "lat": 32.3170, "lng": 34.9340, "region": "השרון"},
    {"name": "אבן יהודה", "name_en": "Even Yehuda", "lat": 32.2700, "lng": 34.8870, "region": "השרון"},
    {"name": "זמורה", "name_en": "Ganot", "lat": 31.9250, "lng": 34.8100, "region": "מרכז"},
    {"name": "בית שמש", "name_en": "Beit Shemesh", "lat": 31.7510, "lng": 34.9887, "region": "ירושלים"},
    {"name": "מעלה אדומים", "name_en": "Ma'ale Adumim", "lat": 31.7760, "lng": 35.3040, "region": "ירושלים"},
    {"name": "ביתר עילית", "name_en": "Beitar Illit", "lat": 31.6930, "lng": 35.1230, "region": "ירושלים"},
    {"name": "גבעת זאב", "name_en": "Givat Ze'ev", "lat": 31.8620, "lng": 35.1740, "region": "ירושלים"},
    {"name": "מבשרת ציון", "name_en": "Mevaseret Zion", "lat": 31.8010, "lng": 35.1530, "region": "ירושלים"},
    {"name": "אריאל", "name_en": "Ariel", "lat": 32.1050, "lng": 35.1750, "region": "יהודה ושומרון"},
    {"name": "ערד", "name_en": "Arad", "lat": 31.2550, "lng": 35.2130, "region": "דרום"},
    {"name": "מצפה רמון", "name_en": "Mitzpe Ramon", "lat": 30.6100, "lng": 34.8020, "region": "דרום"},
    {"name": "אופקים", "name_en": "Ofakim", "lat": 31.3120, "lng": 34.6190, "region": "דרום"},
    {"name": "נתיבות", "name_en": "Netivot", "lat": 31.4210, "lng": 34.5880, "region": "דרום"},
    {"name": "שדרות", "name_en": "Sderot", "lat": 31.5250, "lng": 34.5960, "region": "דרום"},
    {"name": "ירוחם", "name_en": "Yeruham", "lat": 30.9890, "lng": 34.9300, "region": "דרום"},
    {"name": "קריית מלאכי", "name_en": "Kiryat Malakhi", "lat": 31.7300, "lng": 34.7480, "region": "דרום"},
    # Towns & Settlements
    {"name": "רמת השרון", "name_en": "Ramat HaSharon", "lat": 32.1460, "lng": 34.8380, "region": "השרון"},
    {"name": "כפר שמריהו", "name_en": "Kfar Shmaryahu", "lat": 32.1780, "lng": 34.8230, "region": "השרון"},
    {"name": "סביון", "name_en": "Savyon", "lat": 32.0470, "lng": 34.8770, "region": "מרכז"},
    {"name": "עומר", "name_en": "Omer", "lat": 31.2650, "lng": 34.8490, "region": "דרום"},
    {"name": "להבים", "name_en": "Lehavim", "lat": 31.3740, "lng": 34.8150, "region": "דרום"},
    {"name": "מיתר", "name_en": "Meitar", "lat": 31.3260, "lng": 34.9340, "region": "דרום"},
    {"name": "כוכב יאיר", "name_en": "Kokhav Yair", "lat": 32.2220, "lng": 34.9850, "region": "השרון"},
    {"name": "צור יגאל", "name_en": "Tzur Yigal", "lat": 32.2370, "lng": 34.9500, "region": "השרון"},
    {"name": "אלפי מנשה", "name_en": "Alfei Menashe", "lat": 32.1760, "lng": 35.0340, "region": "יהודה ושומרון"},
    {"name": "כפר קאסם", "name_en": "Kafr Qasim", "lat": 32.1140, "lng": 34.9780, "region": "מרכז"},
    {"name": "ג'לג'וליה", "name_en": "Jaljulia", "lat": 32.1550, "lng": 34.9560, "region": "מרכז"},
    {"name": "טירה", "name_en": "Tira", "lat": 32.2340, "lng": 34.9510, "region": "מרכז"},
    {"name": "מעלות-תרשיחא", "name_en": "Ma'alot-Tarshiha", "lat": 33.0166, "lng": 35.2724, "region": "צפון"},
    {"name": "שלומי", "name_en": "Shlomi", "lat": 33.0750, "lng": 35.1430, "region": "צפון"},
    {"name": "מטולה", "name_en": "Metula", "lat": 33.2790, "lng": 35.5830, "region": "צפון"},
    {"name": "ראש פינה", "name_en": "Rosh Pinna", "lat": 32.9690, "lng": 35.5420, "region": "צפון"},
    {"name": "חצור הגלילית", "name_en": "Hazor HaGlilit", "lat": 32.9810, "lng": 35.5460, "region": "צפון"},
    {"name": "בית שאן", "name_en": "Beit She'an", "lat": 32.5010, "lng": 35.4970, "region": "צפון"},
    {"name": "קצרין", "name_en": "Katzrin", "lat": 32.9920, "lng": 35.6910, "region": "גולן"},
    {"name": "גבעת אלה", "name_en": "Givat Ella", "lat": 32.6800, "lng": 35.1500, "region": "צפון"},
    {"name": "דליית אל-כרמל", "name_en": "Daliyat al-Karmel", "lat": 32.6910, "lng": 35.0540, "region": "חיפה"},
    {"name": "עוספייה", "name_en": "Isfiya", "lat": 32.7280, "lng": 35.0630, "region": "חיפה"},
    {"name": "פוריידיס", "name_en": "Fureidis", "lat": 32.6140, "lng": 34.9500, "region": "חיפה"},
    {"name": "ג'סר א-זרקא", "name_en": "Jisr az-Zarqa", "lat": 32.5360, "lng": 34.9040, "region": "חיפה"},
    {"name": "מעיליא", "name_en": "Mi'ilya", "lat": 32.9920, "lng": 35.2360, "region": "צפון"},
    {"name": "פקיעין", "name_en": "Peki'in", "lat": 32.9700, "lng": 35.3300, "region": "צפון"},
    {"name": "יפיע", "name_en": "Yafi", "lat": 32.6790, "lng": 35.2710, "region": "צפון"},
    {"name": "כפר כנא", "name_en": "Kafr Kanna", "lat": 32.7500, "lng": 35.3400, "region": "צפון"},
    {"name": "ריינה", "name_en": "Reineh", "lat": 32.7270, "lng": 35.3130, "region": "צפון"},
    {"name": "דבורייה", "name_en": "Daburiyya", "lat": 32.6850, "lng": 35.3760, "region": "צפון"},
    {"name": "כפר מנדא", "name_en": "Kafr Manda", "lat": 32.8150, "lng": 35.2700, "region": "צפון"},
    {"name": "רהט", "name_en": "Rahat", "lat": 31.3940, "lng": 34.7540, "region": "דרום"},
    {"name": "תל שבע", "name_en": "Tel Sheva", "lat": 31.2510, "lng": 34.8080, "region": "דרום"},
    {"name": "ערערה בנגב", "name_en": "Ar'ara BaNegev", "lat": 31.2830, "lng": 34.8880, "region": "דרום"},
    {"name": "כסיפה", "name_en": "Kuseife", "lat": 31.2340, "lng": 34.9740, "region": "דרום"},
    {"name": "חורה", "name_en": "Hura", "lat": 31.2970, "lng": 34.9160, "region": "דרום"},
    {"name": "לקייה", "name_en": "Lakiya", "lat": 31.3660, "lng": 34.8210, "region": "דרום"},
    {"name": "שגב-שלום", "name_en": "Segev-Shalom", "lat": 31.2500, "lng": 34.8600, "region": "דרום"},
    # Kibbutzim & Moshavim
    {"name": "קיבוץ עין גדי", "name_en": "Ein Gedi", "lat": 31.4660, "lng": 35.3810, "region": "דרום"},
    {"name": "קיבוץ דגניה", "name_en": "Degania", "lat": 32.7110, "lng": 35.5770, "region": "צפון"},
    {"name": "קיבוץ גבעת ברנר", "name_en": "Givat Brenner", "lat": 31.8620, "lng": 34.7990, "region": "מרכז"},
    {"name": "קיבוץ נחשולים", "name_en": "Nahsholim", "lat": 32.6170, "lng": 34.8930, "region": "חיפה"},
    {"name": "מושב בן שמן", "name_en": "Ben Shemen", "lat": 31.9480, "lng": 34.9400, "region": "מרכז"},
    {"name": "גן יבנה", "name_en": "Gan Yavne", "lat": 31.7870, "lng": 34.7050, "region": "מרכז"},
    {"name": "גבעת עדה", "name_en": "Givat Ada", "lat": 32.4950, "lng": 34.9500, "region": "חיפה"},
    {"name": "עין הוד", "name_en": "Ein Hod", "lat": 32.6970, "lng": 34.9870, "region": "חיפה"},
    # Development Towns
    {"name": "יוקנעם", "name_en": "Yokneam", "lat": 32.6592, "lng": 35.1089, "region": "צפון"},
    {"name": "אור עקיבא", "name_en": "Or Akiva", "lat": 32.5060, "lng": 34.9200, "region": "חיפה"},
    {"name": "גבעת אולגה", "name_en": "Givat Olga", "lat": 32.4490, "lng": 34.8760, "region": "חיפה"},
    # Religious Cities
    {"name": "בית אל", "name_en": "Beit El", "lat": 31.9420, "lng": 35.2230, "region": "יהודה ושומרון"},
    {"name": "עמנואל", "name_en": "Emanuel", "lat": 32.1580, "lng": 35.1510, "region": "יהודה ושומרון"},
    {"name": "קדומים", "name_en": "Kedumim", "lat": 32.1660, "lng": 35.1600, "region": "יהודה ושומרון"},
    {"name": "קרני שומרון", "name_en": "Karnei Shomron", "lat": 32.1710, "lng": 35.0970, "region": "יהודה ושומרון"},
    # Gush Dan Area
    {"name": "אזור", "name_en": "Azor", "lat": 32.0240, "lng": 34.7930, "region": "תל אביב"},
    {"name": "תל אביב", "name_en": "Tel Aviv", "lat": 32.0853, "lng": 34.7818, "region": "תל אביב"},
    {"name": "יפו", "name_en": "Jaffa", "lat": 32.0500, "lng": 34.7560, "region": "תל אביב"},
    {"name": "רמת אביב", "name_en": "Ramat Aviv", "lat": 32.1130, "lng": 34.7970, "region": "תל אביב"},
    {"name": "נווה צדק", "name_en": "Neve Tzedek", "lat": 32.0620, "lng": 34.7660, "region": "תל אביב"},
    # Sharon Area
    {"name": "תל מונד", "name_en": "Tel Mond", "lat": 32.2550, "lng": 34.9200, "region": "השרון"},
    {"name": "נורדיה", "name_en": "Nordiya", "lat": 32.2010, "lng": 34.8620, "region": "השרון"},
    {"name": "שרונה", "name_en": "Sharona", "lat": 32.1970, "lng": 34.8990, "region": "השרון"},
    {"name": "גבעת חיים", "name_en": "Givat Haim", "lat": 32.3980, "lng": 34.8990, "region": "השרון"},
    {"name": "בית יצחק", "name_en": "Beit Yitzhak", "lat": 32.2840, "lng": 34.8730, "region": "השרון"},
    # Galilee Villages
    {"name": "כפר תבור", "name_en": "Kfar Tavor", "lat": 32.6930, "lng": 35.4200, "region": "צפון"},
    {"name": "שבלי", "name_en": "Shibli", "lat": 32.6970, "lng": 35.3740, "region": "צפון"},
    {"name": "עילוט", "name_en": "Ilut", "lat": 32.7250, "lng": 35.2420, "region": "צפון"},
    {"name": "כאבול", "name_en": "Kabul", "lat": 32.8700, "lng": 35.2170, "region": "צפון"},
    {"name": "מג'ד אל-כרום", "name_en": "Majd al-Krum", "lat": 32.9200, "lng": 35.2450, "region": "צפון"},
    {"name": "דיר אל-אסד", "name_en": "Deir al-Asad", "lat": 32.9320, "lng": 35.2680, "region": "צפון"},
    {"name": "כפר יאסיף", "name_en": "Kafr Yasif", "lat": 32.9530, "lng": 35.1600, "region": "צפון"},
    {"name": "ג'דיידה-מכר", "name_en": "Judeida-Makr", "lat": 32.9260, "lng": 35.1530, "region": "צפון"},
    {"name": "אבו סנאן", "name_en": "Abu Sinan", "lat": 32.9530, "lng": 35.1760, "region": "צפון"},
    {"name": "ירכא", "name_en": "Yarka", "lat": 32.9570, "lng": 35.2020, "region": "צפון"},
    {"name": "חורפיש", "name_en": "Hurfeish", "lat": 33.0220, "lng": 35.3440, "region": "צפון"},
    {"name": "בית ג'ן", "name_en": "Beit Jann", "lat": 32.9570, "lng": 35.3770, "region": "צפון"},
    # Negev & South
    {"name": "מעגלים", "name_en": "Ma'agalim", "lat": 31.4120, "lng": 34.5070, "region": "דרום"},
    {"name": "תקומה", "name_en": "Tkuma", "lat": 31.4080, "lng": 34.5470, "region": "דרום"},
    {"name": "גבולות", "name_en": "Gevulot", "lat": 31.2260, "lng": 34.4160, "region": "דרום"},
    # Judean Hills
    {"name": "אפרת", "name_en": "Efrat", "lat": 31.6530, "lng": 35.1610, "region": "ירושלים"},
    {"name": "קריית ארבע", "name_en": "Kiryat Arba", "lat": 31.5290, "lng": 35.1190, "region": "ירושלים"},
    {"name": "טקוע", "name_en": "Tekoa", "lat": 31.6350, "lng": 35.2260, "region": "ירושלים"},
    # Coastal Cities
    {"name": "עין כרם", "name_en": "Ein Kerem", "lat": 31.7640, "lng": 35.1610, "region": "ירושלים"},
    {"name": "מוצא עילית", "name_en": "Motza Illit", "lat": 31.7870, "lng": 35.1530, "region": "ירושלים"},
    # Golan Heights
    {"name": "חד נס", "name_en": "Had Nes", "lat": 32.7540, "lng": 35.6590, "region": "גולן"},
    {"name": "אל-רום", "name_en": "El Rom", "lat": 33.1960, "lng": 35.7920, "region": "גולן"},
    {"name": "מג'דל שמס", "name_en": "Majdal Shams", "lat": 33.2690, "lng": 35.7660, "region": "גולן"},
    {"name": "מסעדה", "name_en": "Mas'ade", "lat": 33.2310, "lng": 35.7630, "region": "גולן"},
    {"name": "בוקעאתא", "name_en": "Buq'ata", "lat": 33.2020, "lng": 35.7680, "region": "גולן"},
    # More Southern
    {"name": "קריית אקרון", "name_en": "Kiryat Ekron", "lat": 31.8610, "lng": 34.7930, "region": "מרכז"},
    {"name": "בית דגן", "name_en": "Beit Dagan", "lat": 31.9930, "lng": 34.8330, "region": "מרכז"},
    {"name": "בארותיים", "name_en": "Be'erotayim", "lat": 32.1860, "lng": 34.8480, "region": "השרון"},
    # Jordan Valley
    {"name": "בקעת הירדן", "name_en": "Jordan Valley", "lat": 32.2650, "lng": 35.5370, "region": "צפון"},
    {"name": "מחולה", "name_en": "Mehola", "lat": 32.3350, "lng": 35.5060, "region": "צפון"},
    # Additional Missing Cities
    {"name": "יהוד", "name_en": "Yehud", "lat": 32.0330, "lng": 34.8830, "region": "מרכז"},
    {"name": "כפר חב\"ד", "name_en": "Kfar Chabad", "lat": 31.9850, "lng": 34.8460, "region": "מרכז"},
    {"name": "נס הרים", "name_en": "Nes Harim", "lat": 31.7330, "lng": 35.0730, "region": "ירושלים"},
    {"name": "צור הדסה", "name_en": "Tzur Hadassah", "lat": 31.7160, "lng": 35.1020, "region": "ירושלים"},
    {"name": "בית נחמיה", "name_en": "Beit Nechemya", "lat": 31.8590, "lng": 34.9510, "region": "מרכז"},
    {"name": "חריש", "name_en": "Harish", "lat": 32.4570, "lng": 35.0440, "region": "מרכז"},
    {"name": "עין שמר", "name_en": "Ein Shemer", "lat": 32.4370, "lng": 35.0090, "region": "חיפה"},
    {"name": "עמק חפר", "name_en": "Emek Hefer", "lat": 32.3690, "lng": 34.9100, "region": "השרון"},
    {"name": "גנים", "name_en": "Ganim", "lat": 32.2410, "lng": 34.9770, "region": "השרון"},
]

# Region coordinates for fallback
REGION_CENTERS = {
    "תל אביב": {"lat": 32.08, "lng": 34.78, "radius_km": 20},
    "מרכז": {"lat": 32.07, "lng": 34.82, "radius_km": 40},
    "חיפה": {"lat": 32.8, "lng": 35.0, "radius_km": 30},
    "צפון": {"lat": 32.9, "lng": 35.3, "radius_km": 60},
    "השרון": {"lat": 32.3, "lng": 34.9, "radius_km": 30},
    "ירושלים": {"lat": 31.77, "lng": 35.21, "radius_km": 40},
    "דרום": {"lat": 31.25, "lng": 34.79, "radius_km": 80},
    "יהודה ושומרון": {"lat": 32.1, "lng": 35.15, "radius_km": 50},
    "גולן": {"lat": 33.0, "lng": 35.75, "radius_km": 30},
    # Legacy names (for backward compatibility)
    "חיפה והקריות": {"lat": 32.8, "lng": 35.0, "radius_km": 30},
    "ירושלים והסביבה": {"lat": 31.77, "lng": 35.21, "radius_km": 40},
    "שרון": {"lat": 32.3, "lng": 34.9, "radius_km": 30},
    "שומרון": {"lat": 32.15, "lng": 35.15, "radius_km": 50},
}

# Region name mappings - which locality regions belong to each search region
REGION_LOCALITY_MAPPING = {
    "תל אביב": ["תל אביב"],
    "מרכז": ["מרכז"],
    "חיפה": ["חיפה"],
    "צפון": ["צפון"],
    "השרון": ["השרון"],
    "ירושלים": ["ירושלים"],
    "דרום": ["דרום"],
    "יהודה ושומרון": ["יהודה ושומרון"],
    "גולן": ["גולן"],
    # Legacy names (backward compatibility)
    "חיפה והקריות": ["חיפה"],
    "ירושלים והסביבה": ["ירושלים"],
    "שרון": ["השרון"],
    "שומרון": ["יהודה ושומרון"],
}

# Complete list of all Israeli cities/settlements (synced with frontend israeliLocalities.js)
# Cities not in ISRAEL_LOCALITIES get approximate coordinates from region center
ALL_CITY_NAMES = [
    # תל אביב
    {"name": "חירייה", "region": "תל אביב"},
    # מרכז
    {"name": "באר יעקב", "region": "מרכז"},
    {"name": "קריית עקרון", "region": "מרכז"},
    {"name": "כפר ורבורג", "region": "מרכז"},
    {"name": "כפר מלל", "region": "מרכז"},
    {"name": "גבעת חן", "region": "מרכז"},
    {"name": "גליל ים", "region": "מרכז"},
    {"name": "ארסוף", "region": "מרכז"},
    {"name": "געש", "region": "מרכז"},
    {"name": "יקום", "region": "מרכז"},
    {"name": "בית חירות", "region": "מרכז"},
    {"name": "אודים", "region": "מרכז"},
    {"name": "פולג", "region": "מרכז"},
    {"name": "אליכין", "region": "מרכז"},
    {"name": "בארות יצחק", "region": "מרכז"},
    {"name": "יד חנה", "region": "מרכז"},
    {"name": "צור משה", "region": "מרכז"},
    {"name": "צור נתן", "region": "מרכז"},
    {"name": "גבעת השלושה", "region": "מרכז"},
    {"name": "משמר השרון", "region": "מרכז"},
    {"name": "רמות השבים", "region": "מרכז"},
    {"name": "עין שריד", "region": "מרכז"},
    {"name": "כפר ברא", "region": "מרכז"},
    {"name": "נורדיה", "region": "מרכז"},
    # חיפה
    {"name": "בית שערים", "region": "חיפה"},
    {"name": "יגור", "region": "חיפה"},
    {"name": "רכסים", "region": "חיפה"},
    {"name": "דלית אל-כרמל", "region": "חיפה"},
    {"name": "עוספיה", "region": "חיפה"},
    {"name": "בית אורן", "region": "חיפה"},
    {"name": "ניר עציון", "region": "חיפה"},
    {"name": "כפר גלים", "region": "חיפה"},
    # צפון
    {"name": "יקנעם", "region": "צפון"},
    {"name": "נהלל", "region": "צפון"},
    {"name": "שבלי - אום אל-גנם", "region": "צפון"},
    {"name": "דבוריה", "region": "צפון"},
    {"name": "איכסאל", "region": "צפון"},
    {"name": "משהד", "region": "צפון"},
    {"name": "עין מאהל", "region": "צפון"},
    {"name": "יפעת", "region": "צפון"},
    {"name": "מזרע", "region": "צפון"},
    {"name": "גניגר", "region": "צפון"},
    {"name": "תל עדשים", "region": "צפון"},
    {"name": "שדה נחום", "region": "צפון"},
    {"name": "מרחביה", "region": "צפון"},
    {"name": "עין השופט", "region": "צפון"},
    {"name": "מגידו", "region": "צפון"},
    {"name": "רמת דוד", "region": "צפון"},
    {"name": "הזורעים", "region": "צפון"},
    {"name": "שריד", "region": "צפון"},
    {"name": "גבת", "region": "צפון"},
    {"name": "אלון הגליל", "region": "צפון"},
    {"name": "אלוני אבא", "region": "צפון"},
    {"name": "ציפורי", "region": "צפון"},
    {"name": "הושעיה", "region": "צפון"},
    {"name": "תמרת", "region": "צפון"},
    {"name": "סואעד", "region": "צפון"},
    {"name": "כפר גלעדי", "region": "צפון"},
    {"name": "דפנה", "region": "צפון"},
    {"name": "שניר", "region": "צפון"},
    {"name": "דן", "region": "צפון"},
    {"name": "הגושרים", "region": "צפון"},
    {"name": "כפר בלום", "region": "צפון"},
    {"name": "עמיר", "region": "צפון"},
    {"name": "שאר ישוב", "region": "צפון"},
    {"name": "נאות מרדכי", "region": "צפון"},
    {"name": "יסוד המעלה", "region": "צפון"},
    {"name": "אילון", "region": "צפון"},
    {"name": "מעיין ברוך", "region": "צפון"},
    {"name": "משמר הירדן", "region": "צפון"},
    {"name": "גדות", "region": "צפון"},
    {"name": "נחף", "region": "צפון"},
    {"name": "ג'יש", "region": "צפון"},
    {"name": "סאסא", "region": "צפון"},
    {"name": "בר יוחאי", "region": "צפון"},
    {"name": "מירון", "region": "צפון"},
    {"name": "כפר חנניה", "region": "צפון"},
    {"name": "עמוקה", "region": "צפון"},
    {"name": "ברעם", "region": "צפון"},
    {"name": "טורעאן", "region": "צפון"},
    {"name": "עיילבון", "region": "צפון"},
    {"name": "דיר חנא", "region": "צפון"},
    {"name": "סח'נין", "region": "צפון"},
    {"name": "מגאר", "region": "צפון"},
    {"name": "כאוכב אבו אל-היג'א", "region": "צפון"},
    {"name": "מגדל", "region": "צפון"},
    {"name": "גינוסר", "region": "צפון"},
    {"name": "דגניה א", "region": "צפון"},
    {"name": "דגניה ב", "region": "צפון"},
    {"name": "כנרת", "region": "צפון"},
    {"name": "כפר נחום", "region": "צפון"},
    {"name": "אמנון", "region": "צפון"},
    {"name": "עין גב", "region": "צפון"},
    {"name": "תל קציר", "region": "צפון"},
    {"name": "מעגן", "region": "צפון"},
    {"name": "חוקוק", "region": "צפון"},
    {"name": "לביא", "region": "צפון"},
    {"name": "כפר זיתים", "region": "צפון"},
    {"name": "ארבל", "region": "צפון"},
    {"name": "מצפה", "region": "צפון"},
    {"name": "פקיעין החדשה", "region": "צפון"},
    {"name": "כישור", "region": "צפון"},
    {"name": "לפידות", "region": "צפון"},
    {"name": "יחיעם", "region": "צפון"},
    {"name": "כברי", "region": "צפון"},
    {"name": "גורן", "region": "צפון"},
    {"name": "חניתה", "region": "צפון"},
    {"name": "אדמית", "region": "צפון"},
    {"name": "סער", "region": "צפון"},
    {"name": "לוחמי הגטאות", "region": "צפון"},
    {"name": "עברון", "region": "צפון"},
    {"name": "לימן", "region": "צפון"},
    {"name": "גשר הזיו", "region": "צפון"},
    {"name": "בצת", "region": "צפון"},
    {"name": "מצובה", "region": "צפון"},
    {"name": "שמרת", "region": "צפון"},
    {"name": "בוסתן הגליל", "region": "צפון"},
    {"name": "יערה", "region": "צפון"},
    {"name": "אבירים", "region": "צפון"},
    {"name": "מתת", "region": "צפון"},
    {"name": "הילה", "region": "צפון"},
    {"name": "כפר ורדים", "region": "צפון"},
    {"name": "מעלה צביה", "region": "צפון"},
    {"name": "שורשים", "region": "צפון"},
    {"name": "מנוף", "region": "צפון"},
    {"name": "הרדוף", "region": "צפון"},
    {"name": "עצמון שגב", "region": "צפון"},
    {"name": "מכמנים", "region": "צפון"},
    {"name": "יובלים", "region": "צפון"},
    {"name": "גילון", "region": "צפון"},
    # ירושלים
    {"name": "מודיעין עילית", "region": "ירושלים"},
    {"name": "אבו גוש", "region": "ירושלים"},
    {"name": "עין נקובא", "region": "ירושלים"},
    {"name": "קריית יערים", "region": "ירושלים"},
    {"name": "בית זית", "region": "ירושלים"},
    {"name": "בית מאיר", "region": "ירושלים"},
    {"name": "שורש", "region": "ירושלים"},
    {"name": "נווה אילן", "region": "ירושלים"},
    {"name": "רמת רזיאל", "region": "ירושלים"},
    {"name": "גבעת יערים", "region": "ירושלים"},
    {"name": "נטף", "region": "ירושלים"},
    {"name": "כסלון", "region": "ירושלים"},
    {"name": "נחם", "region": "ירושלים"},
    {"name": "צובה", "region": "ירושלים"},
    {"name": "רמות", "region": "ירושלים"},
    {"name": "עין ראפה", "region": "ירושלים"},
    {"name": "אורה", "region": "ירושלים"},
    {"name": "עמינדב", "region": "ירושלים"},
    {"name": "בר גיורא", "region": "ירושלים"},
    {"name": "זנוח", "region": "ירושלים"},
    {"name": "כפר אוריה", "region": "ירושלים"},
    {"name": "תרום", "region": "ירושלים"},
    {"name": "הראל", "region": "ירושלים"},
    {"name": "אשתאול", "region": "ירושלים"},
    # דרום
    {"name": "ניר עוז", "region": "דרום"},
    {"name": "נחל עוז", "region": "דרום"},
    {"name": "כפר עזה", "region": "דרום"},
    {"name": "בארי", "region": "דרום"},
    {"name": "רעים", "region": "דרום"},
    {"name": "כיסופים", "region": "דרום"},
    {"name": "עין השלושה", "region": "דרום"},
    {"name": "ניר יצחק", "region": "דרום"},
    {"name": "מגן", "region": "דרום"},
    {"name": "אוהד", "region": "דרום"},
    {"name": "סופה", "region": "דרום"},
    {"name": "יבול", "region": "דרום"},
    {"name": "תלמי יוסף", "region": "דרום"},
    {"name": "פרי גן", "region": "דרום"},
    {"name": "שדה אברהם", "region": "דרום"},
    {"name": "ארז", "region": "דרום"},
    {"name": "יד מרדכי", "region": "דרום"},
    {"name": "נתיב העשרה", "region": "דרום"},
    {"name": "זיקים", "region": "דרום"},
    {"name": "כרמיה", "region": "דרום"},
    {"name": "מבטחים", "region": "דרום"},
    {"name": "תושיה", "region": "דרום"},
    {"name": "ניר עם", "region": "דרום"},
    {"name": "אשכול", "region": "דרום"},
    {"name": "מפלסים", "region": "דרום"},
    {"name": "עלומים", "region": "דרום"},
    {"name": "דקלה", "region": "דרום"},
    {"name": "מבקיעים", "region": "דרום"},
    {"name": "ברור חיל", "region": "דרום"},
    {"name": "שדה ניצן", "region": "דרום"},
    {"name": "חולית", "region": "דרום"},
    {"name": "יתד", "region": "דרום"},
    {"name": "שובה", "region": "דרום"},
    {"name": "כפר מרדכי", "region": "דרום"},
    {"name": "אביגדור", "region": "דרום"},
    {"name": "בית שקמה", "region": "דרום"},
    {"name": "ברכיה", "region": "דרום"},
    {"name": "גיאה", "region": "דרום"},
    {"name": "גבעתי", "region": "דרום"},
    {"name": "מנוחה", "region": "דרום"},
    {"name": "משמר דוד", "region": "דרום"},
    {"name": "נגבה", "region": "דרום"},
    {"name": "עוצם", "region": "דרום"},
    {"name": "עזריקם", "region": "דרום"},
    {"name": "כנות", "region": "דרום"},
    {"name": "חצב", "region": "דרום"},
    {"name": "כפר אחים", "region": "דרום"},
    {"name": "כפר הרי\"ף", "region": "דרום"},
    {"name": "שתולים", "region": "דרום"},
    {"name": "נועם", "region": "דרום"},
    {"name": "כפר הנגיד", "region": "דרום"},
    {"name": "בן זכאי", "region": "דרום"},
    {"name": "כפר אביב", "region": "דרום"},
    {"name": "גבעות בר", "region": "דרום"},
    {"name": "שגב שלום", "region": "דרום"},
    {"name": "נווה מדבר", "region": "דרום"},
    {"name": "עידן הנגב", "region": "דרום"},
    {"name": "ניצנה", "region": "דרום"},
    {"name": "קדש ברנע", "region": "דרום"},
    {"name": "עזוז", "region": "דרום"},
    {"name": "אשלים", "region": "דרום"},
    {"name": "רתמים", "region": "דרום"},
    {"name": "שדה בוקר", "region": "דרום"},
    {"name": "מדרשת בן גוריון", "region": "דרום"},
    {"name": "עין גדי", "region": "דרום"},
    {"name": "נווה זוהר", "region": "דרום"},
    {"name": "יטבתה", "region": "דרום"},
    {"name": "באר אורה", "region": "דרום"},
    {"name": "קטורה", "region": "דרום"},
    {"name": "גרופית", "region": "דרום"},
    {"name": "סמר", "region": "דרום"},
    {"name": "אליפז", "region": "דרום"},
    {"name": "לוטן", "region": "דרום"},
    {"name": "נאות סמדר", "region": "דרום"},
    {"name": "עין יהב", "region": "דרום"},
    {"name": "ספיר", "region": "דרום"},
    {"name": "פארן", "region": "דרום"},
    {"name": "עין תמר", "region": "דרום"},
    {"name": "חצבה", "region": "דרום"},
    {"name": "עידן", "region": "דרום"},
    # יהודה ושומרון
    {"name": "אלקנה", "region": "יהודה ושומרון"},
    {"name": "עפרה", "region": "יהודה ושומרון"},
    {"name": "שילה", "region": "יהודה ושומרון"},
    {"name": "יצהר", "region": "יהודה ושומרון"},
    {"name": "ברכה", "region": "יהודה ושומרון"},
    {"name": "איתמר", "region": "יהודה ושומרון"},
    {"name": "עלי", "region": "יהודה ושומרון"},
    {"name": "רבבה", "region": "יהודה ושומרון"},
    {"name": "גינות שומרון", "region": "יהודה ושומרון"},
    {"name": "מגרון", "region": "יהודה ושומרון"},
    {"name": "פסגות", "region": "יהודה ושומרון"},
    {"name": "עטרת", "region": "יהודה ושומרון"},
    {"name": "דולב", "region": "יהודה ושומרון"},
    {"name": "טלמון", "region": "יהודה ושומרון"},
    {"name": "נחליאל", "region": "יהודה ושומרון"},
    {"name": "חלמיש", "region": "יהודה ושומרון"},
    {"name": "נווה צוף", "region": "יהודה ושומרון"},
    {"name": "עלי זהב", "region": "יהודה ושומרון"},
    {"name": "אורנית", "region": "יהודה ושומרון"},
    {"name": "שערי תקווה", "region": "יהודה ושומרון"},
    {"name": "צופים", "region": "יהודה ושומרון"},
    {"name": 'ניל"י', "region": "יהודה ושומרון"},
    {"name": "כפר האורנים", "region": "יהודה ושומרון"},
    {"name": "בית חורון", "region": "יהודה ושומרון"},
    {"name": "מכבים", "region": "יהודה ושומרון"},
    {"name": "לפיד", "region": "יהודה ושומרון"},
    {"name": "נופים", "region": "יהודה ושומרון"},
    {"name": "חשמונאים", "region": "יהודה ושומרון"},
    {"name": "מתתיהו", "region": "יהודה ושומרון"},
    {"name": "אלון שבות", "region": "יהודה ושומרון"},
    {"name": "כפר עציון", "region": "יהודה ושומרון"},
    {"name": "מגדל עוז", "region": "יהודה ושומרון"},
    {"name": "נווה דניאל", "region": "יהודה ושומרון"},
    {"name": "רוש צורים", "region": "יהודה ושומרון"},
    {"name": "בת עין", "region": "יהודה ושומרון"},
    {"name": "תקוע", "region": "יהודה ושומרון"},
    {"name": "נוקדים", "region": "יהודה ושומרון"},
    {"name": "אלעזר", "region": "יהודה ושומרון"},
    {"name": "כרמי צור", "region": "יהודה ושומרון"},
    {"name": "מעון", "region": "יהודה ושומרון"},
    {"name": "סוסיא", "region": "יהודה ושומרון"},
    {"name": "מחולה", "region": "יהודה ושומרון"},
    {"name": "משואה", "region": "יהודה ושומרון"},
    {"name": "שדמות מחולה", "region": "יהודה ושומרון"},
    {"name": "רועי", "region": "יהודה ושומרון"},
    {"name": "חמרה", "region": "יהודה ושומרון"},
    {"name": "בקעות", "region": "יהודה ושומרון"},
    {"name": "גיתית", "region": "יהודה ושומרון"},
    {"name": "גלגל", "region": "יהודה ושומרון"},
    {"name": "יפית", "region": "יהודה ושומרון"},
    {"name": "מבואות יריחו", "region": "יהודה ושומרון"},
    {"name": "נערן", "region": "יהודה ושומרון"},
    {"name": "נטעים", "region": "יהודה ושומרון"},
    {"name": "פצאל", "region": "יהודה ושומרון"},
    {"name": "תומר", "region": "יהודה ושומרון"},
    # גולן
    {"name": "חספין", "region": "גולן"},
    {"name": "אניעם", "region": "גולן"},
    {"name": "אבני איתן", "region": "גולן"},
    {"name": "נווה אטיב", "region": "גולן"},
    {"name": "נמרוד", "region": "גולן"},
    {"name": "אודם", "region": "גולן"},
    {"name": "אל רום", "region": "גולן"},
    {"name": "מרום גולן", "region": "גולן"},
    {"name": "קשת", "region": "גולן"},
    {"name": "יונתן", "region": "גולן"},
    {"name": "אורטל", "region": "גולן"},
    {"name": "שעל", "region": "גולן"},
    {"name": "מבוא חמה", "region": "גולן"},
    {"name": "רמות", "region": "גולן"},
    {"name": "כנף", "region": "גולן"},
    {"name": "אפיק", "region": "גולן"},
    {"name": "גשור", "region": "גולן"},
    {"name": "נאות גולן", "region": "גולן"},
    {"name": "גבעת יואב", "region": "גולן"},
    {"name": "עין זיוון", "region": "גולן"},
    {"name": "אליעד", "region": "גולן"},
    {"name": "מעלה גמלא", "region": "גולן"},
    {"name": "נטור", "region": "גולן"},
    {"name": "בני יהודה", "region": "גולן"},
    {"name": "קדמת צבי", "region": "גולן"},
    # השרון
    {"name": "צור יצחק", "region": "השרון"},
    {"name": "תל יצחק", "region": "השרון"},
    {"name": "כפר נטר", "region": "השרון"},
    {"name": "קריית השרון", "region": "השרון"},
    {"name": "עין ורד", "region": "השרון"},
    {"name": "כפר הרא\"ה", "region": "השרון"},
    {"name": "אחיטוב", "region": "השרון"},
    {"name": "אביחיל", "region": "השרון"},
    {"name": "שער אפריים", "region": "השרון"},
    {"name": "עין חרוד", "region": "השרון"},
    {"name": "בית אלפא", "region": "השרון"},
    {"name": "חפציבה", "region": "השרון"},
    {"name": "תל יוסף", "region": "השרון"},
    {"name": "מעברות", "region": "השרון"},
    {"name": "בית הלוי", "region": "השרון"},
    {"name": "חרות", "region": "השרון"},
    {"name": "ניצני עוז", "region": "השרון"},
    {"name": "בני דרור", "region": "השרון"},
    {"name": "הדר עם", "region": "השרון"},
    {"name": "ינוב", "region": "השרון"},
    {"name": "שדה ורבורג", "region": "השרון"},
    {"name": "עולש", "region": "השרון"},
    {"name": "בית יהושע", "region": "השרון"},
    {"name": "הוגה", "region": "השרון"},
    {"name": "רשפון", "region": "השרון"},
    {"name": "שפיים", "region": "השרון"},
]

# Build combined localities list: precise coords from ISRAEL_LOCALITIES + approximate from ALL_CITY_NAMES
_coords_lookup = {loc["name"]: loc for loc in ISRAEL_LOCALITIES}

def _build_all_localities():
    """Build complete list with all cities. Missing coords get region center approximation."""
    all_locs = list(ISRAEL_LOCALITIES)
    existing_names = {loc["name"] for loc in ISRAEL_LOCALITIES}
    for city in ALL_CITY_NAMES:
        if city["name"] not in existing_names:
            region_center = REGION_CENTERS.get(city["region"], {})
            all_locs.append({
                "name": city["name"],
                "name_en": "",
                "lat": region_center.get("lat", 31.5),
                "lng": region_center.get("lng", 34.8),
                "region": city["region"],
                "approximate": True,
            })
            existing_names.add(city["name"])
    return all_locs

ALL_LOCALITIES = _build_all_localities()

def get_region_info(region_name: str):
    """Get region center coordinates and radius. Returns None if not a region."""
    return REGION_CENTERS.get(region_name)

def get_cities_in_region(region_name: str):
    """Get all city names that belong to a region"""
    locality_regions = REGION_LOCALITY_MAPPING.get(region_name)
    if not locality_regions:
        return []
    cities = []
    for loc in ALL_LOCALITIES:
        if loc.get("region") in locality_regions:
            cities.append(loc["name"])
    return cities

def get_locality_coords(name: str):
    """Get coordinates for a locality name"""
    name_lower = name.strip()
    for loc in ALL_LOCALITIES:
        if loc["name"] == name_lower or loc.get("name_en", "").lower() == name_lower.lower():
            return {"lat": loc["lat"], "lng": loc["lng"], "region": loc.get("region", "")}
    # Partial match
    for loc in ALL_LOCALITIES:
        if name_lower in loc["name"] or loc["name"] in name_lower:
            return {"lat": loc["lat"], "lng": loc["lng"], "region": loc.get("region", "")}
    return None

def search_localities(query: str, limit: int = 20):
    """Search localities by name"""
    results = []
    q = query.strip().lower()
    for loc in ALL_LOCALITIES:
        if q in loc["name"] or q in loc.get("name_en", "").lower():
            results.append(loc)
    return results[:limit]

def get_all_localities():
    """Get all localities"""
    return ALL_LOCALITIES
